version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  mongo_data: